services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: go-out-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 007787898
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
